// app/layout.js
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import { ClientProvider } from "../context/ClientProvider";

export const metadata = {
  title: "انصاف تابلو",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className={`antialiased min-h-screen  flex flex-col`}>
        <ClientProvider>
          <Header />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </ClientProvider>

      </body>
    </html>
  );
}